name: clang-format-cn Check
on: workflow_dispatch
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'prov/opx'
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Run clang-format style check for C/C++/Protobuf programs (Cornelis Networks-specific).
      uses: jidicula/clang-format-action@81356ae1ab1ef29a26ff0409930e76f84b3a239b # v4.10.2
      with:
        clang-format-version: '15'
        check-path: ${{ matrix.path }}
